### ISSUE TITLE
Add SpecificType field to server Request

### ISSUE THREAD

**Issue by mohitsuman** [mohitsuman/adapters-vscode#34]
Currently the server just accepts the following fields: `id`, `serverType`, `attributes`.

Need to add `SpecificType` field to configure server Type and related informations from the object returned.

**Comment by robstryker** [comment]
Hey mohit:

I don't really know what this enhancement request means. What exactly is "specific type" ?

**Comment by mohitsuman** [comment]
@robstryker For the current implementation, we have the serverType which returns the string `serverType: org.jboss.ide.eclipse.as.wildfly.120`. For displaying the data on UI, we will displaying the SpecificType, which basically in this case will be *Wildfly*.

Say in next iteration, the next server will be OpenShift, the SpecificType will be *OpenShift*.  It basically is the type of the server we are catering to.

**Comment by robstryker** [comment]
Changes to the SSP were made that should allow this to happen on your end now.
